//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::bus::Entity as Bus;
pub use super::route::Entity as Route;
pub use super::seat::Entity as Seat;
pub use super::ticket::Entity as Ticket;
pub use super::trip::Entity as Trip;
pub use super::user::Entity as User;
